version: "3.9"
services:
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: funny_cafe
    ports:
      - "5431:5431"
    restart: unless-stopped

  django:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:admin@db:5432/funny_cafe
    volumes:
      - ./myproject:/app

volumes:
  postgres_data:
